CREATE TABLE IF NOT EXISTS `TableNameReplace` (
    `id` int(11) NOT NULL ,
    `photo` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `fb_id` varchar(500) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `name_bangla` varchar(500) NULL,
    `name` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `student_id` varchar(10) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `hall` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `batch` varchar(300) NULL,
    `phone` varchar(11) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `email` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `blood` varchar(5) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `session` varchar(100) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `address` varchar(1000) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `district` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `address_bangla` varchar(1000) NULL,
    `Password` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `job_ins` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `job_p` varchar(300) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `LastUpdateTime` varchar(300) NULL,
    `role` varchar(300) NULL,
    `birth` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `father_name` varchar(150) CHARACTER SET utf8 COLLATE utf8_unicode_ci NULL,
    `active` int(1) NULL,
    `showing` int(1) NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `student_id` (`student_id`)
    ) ENGINE=MyISAM DEFAULT CHARSET=utf8;