# Generated by Django 4.2.5 on 2023-09-17 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='title',
        ),
        migrations.AddField(
            model_name='upload',
            name='category',
            field=models.CharField(choices=[('jpgtopdf', 'JPG to PDF'), ('psd', 'PDF SPLIT DEFINED'), ('psa', 'PDF SPLIT ALL')], default='', max_length=50),
        ),
    ]
