# Generated by Django 4.2.5 on 2023-09-17 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_remove_upload_title_upload_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='category',
        ),
    ]
