# Generated by Django 4.2.5 on 2023-09-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_remove_upload_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/', verbose_name='Select File'),
        ),
    ]
